[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "ExtendedChoice"
versionNumber = "1.0.0"
description = "Hades 2 port of LootChoiceExtender from Hades 1 created by Magic_Gonads."
websiteUrl = "https://github.com/zanncdwbl/zanncModMain_Hades"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ModUtil = "3.1.0"
Hell2Modding-Hell2Modding = "1.0.28"
SGG_Modding-ModUtil = "3.1.1"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ENVY = "1.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]