[config]
schemaVersion = "0..1"


[package]
namespace = "zannc"
name = "ExtendedChoice"
versionNumber = "0.1"
description = "Hades 2 port of LootChoiceExtender from Hades 1 created by Magic_Gonads."
websiteUrl = "https://github.com/zanncdwbl/zanncModMain_Hades"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ModUtil = "3.1.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]